# Generated by Django 5.2.1 on 2026-03-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.AddField(
            model_name='slider',
            name='desktop_image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/desktop/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/mobile/'),
        ),
    ]
