# Generated by Django 5.2.1 on 2026-03-15 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_slider_image_slider_desktop_image_and_more'),
        ('courses', '0002_remove_comboproduct_book_sets_delete_bookset'),
    ]

    operations = [
        migrations.AddField(
            model_name='demofile',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_files', to='courses.book'),
        ),
        migrations.AddField(
            model_name='demolecture',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_lectures', to='courses.lecture'),
        ),
    ]
