# Generated by Django 5.2.5 on 2026-03-19 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_demofile_book_demolecture_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrbitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='2-3 word text, e.g. CA Certified', max_length=50)),
                ('sub_label', models.CharField(blank=True, help_text='Optional small text, e.g. ICAI Approved', max_length=80)),
                ('icon', models.CharField(help_text='Iconify icon name, e.g. mdi:certificate', max_length=100)),
                ('icon_color', models.CharField(default='#a78bfa', help_text='Hex color for icon, e.g. #a78bfa', max_length=20)),
                ('bg_color', models.CharField(default='#1a1433', help_text='Card background hex color', max_length=20)),
                ('orbit', models.CharField(choices=[('outer', 'Outer Ring'), ('inner', 'Inner Ring')], default='outer', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the ring')),
                ('is_active', models.BooleanField(default=True)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orbit_cards', to='api.slider')),
            ],
            options={
                'ordering': ['orbit', 'order'],
            },
        ),
    ]
