# Generated by Django 5.2.5 on 2026-03-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orbitcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Main text, e.g. Reliance Industries', max_length=80)),
                ('sub_label', models.CharField(blank=True, help_text='Optional second line', max_length=80)),
                ('icon', models.CharField(help_text='Iconify icon name, e.g. mdi:bank', max_length=100)),
                ('icon_color', models.CharField(default='#2563eb', max_length=20)),
                ('bg_color', models.CharField(default='#ffffff', max_length=20)),
                ('position_index', models.PositiveSmallIntegerField(choices=[(0, 'Top Center-Left'), (1, 'Top Right'), (2, 'Middle Left'), (3, 'Middle Right'), (4, 'Bottom Left')], default=0, help_text='0=Top-CenterLeft | 1=Top-Right | 2=Mid-Left | 3=Mid-Right | 4=Bottom-Left')),
                ('is_active', models.BooleanField(default=True)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floating_cards', to='api.slider')),
            ],
            options={
                'ordering': ['position_index'],
                'unique_together': {('slider', 'position_index')},
            },
        ),
        migrations.DeleteModel(
            name='OrbitCard',
        ),
    ]
