# Generated by Django 5.2.5 on 2026-03-11 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name e.g. mdi:web', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('book_type', models.CharField(choices=[('concept', 'Concept Book'), ('question_bank', 'Question Bank'), ('mcq', 'MCQ Book'), ('other', 'Other')], default='concept', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='api.faculty')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='courses.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('batch_type', models.CharField(choices=[('exam_oriented', 'Exam Oriented Batch'), ('regular', 'Regular Batch'), ('power', 'Power Batch')], default='regular', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lectures/')),
                ('description', models.TextField(blank=True)),
                ('batch_details', models.TextField(blank=True, help_text='HTML rich content for batch details tab')),
                ('duration', models.CharField(blank=True, help_text='e.g. 120 Hours', max_length=100)),
                ('total_lectures', models.PositiveIntegerField(blank=True, null=True)),
                ('validity', models.CharField(blank=True, help_text='e.g. 2 Years', max_length=100)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='courses.category')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='api.faculty')),
                ('recommended_books', models.ManyToManyField(blank=True, related_name='recommended_by_lectures', to='courses.book')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LectureCurriculumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='courses.lecture')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='courses.category')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='courses.subject'),
        ),
        migrations.CreateModel(
            name='BookSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('set_price', models.DecimalField(decimal_places=2, help_text='Bundled set price', max_digits=10)),
                ('original_set_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_sets/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('books', models.ManyToManyField(related_name='sets', to='courses.book')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_sets', to='api.faculty')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_sets', to='courses.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='courses.subject'),
        ),
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('course_name', models.CharField(choices=[('ca', 'CA'), ('cma', 'CMA'), ('other', 'Other')], default='ca', max_length=10)),
                ('level', models.CharField(choices=[('final', 'Final'), ('inter', 'Inter'), ('na', 'N/A')], default='final', max_length=10)),
                ('test_type', models.CharField(choices=[('full', 'Full Test'), ('part', 'Part Test'), ('full_part', 'Full + Part Test')], default='full', max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='test_series/')),
                ('description', models.TextField(blank=True)),
                ('total_tests', models.PositiveIntegerField(blank=True, null=True)),
                ('validity', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_series', to='courses.category')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_series', to='api.faculty')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_series', to='courses.subject')),
            ],
            options={
                'verbose_name_plural': 'Test Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='recommended_test_series',
            field=models.ManyToManyField(blank=True, related_name='recommended_by_lectures', to='courses.testseries'),
        ),
        migrations.CreateModel(
            name='ComboProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='combos/')),
                ('description', models.TextField(blank=True)),
                ('combo_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_sets', models.ManyToManyField(blank=True, related_name='combos', to='courses.bookset')),
                ('books', models.ManyToManyField(blank=True, related_name='combos', to='courses.book')),
                ('lectures', models.ManyToManyField(blank=True, related_name='combos', to='courses.lecture')),
                ('test_series', models.ManyToManyField(blank=True, related_name='combos', to='courses.testseries')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LectureVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('gd_android_ios', 'GD / Android / iOS'), ('pendrive', 'Pendrive (PD)'), ('live', 'Live Mode'), ('upcoming', 'Upcoming Batch')], max_length=30)),
                ('language', models.CharField(choices=[('hindi', 'Hindi'), ('english', 'English'), ('both', 'Hindi + English')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='courses.lecture')),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('lecture', 'mode', 'language')},
            },
        ),
    ]
