# Generated by Django 5.2.5 on 2026-03-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comboproduct',
            name='book_sets',
        ),
        migrations.DeleteModel(
            name='BookSet',
        ),
    ]
