# Generated by Django 5.2.5 on 2026-03-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add_to_cart', 'Add to Cart'), ('buy_now', 'Buy Now')], max_length=20)),
                ('product_id', models.CharField(blank=True, max_length=100)),
                ('product_type', models.CharField(blank=True, max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=500)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variant_mode', models.CharField(blank=True, max_length=100)),
                ('variant_language', models.CharField(blank=True, max_length=100)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('user_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Activity',
                'verbose_name_plural': 'Product Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
